import { createSlice } from '@reduxjs/toolkit';

import { PublicKey } from '@solana/web3.js'

export interface ItemNftData {
  address: PublicKey,
  game: PublicKey,
  name: string,
  description: string,
  image: string,
}

export interface ItemsNftStoreState {
  inProgress: PublicKey[],
  loaded: ItemNftData[],
  failed: PublicKey[]
}

const initialState: ItemsNftStoreState = {
  inProgress: [],
  loaded: [],
  failed: []
};

export const itemsNftStoreSlice = createSlice({
  name: 'itemsNftStore',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {

  },
});


export default itemsNftStoreSlice.reducer;
