[programs.localnet]
asylum = "Ec5HRTfsozgfQerig5DTsKqGL3MkZ3jcdohb3qYXwzMN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/corwin/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
