import { createSlice } from '@reduxjs/toolkit';

export interface MarketplacePageState {
}

const initialState: MarketplacePageState = {
};

export const marketplacePageSlice = createSlice({
  name: 'marketplacePage',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {

  },
});


export default marketplacePageSlice.reducer;
