import { createSelector, createSlice } from '@reduxjs/toolkit';
import { PublicKey } from '@solana/web3.js'
import { RootState } from '../../app/store';
import { dummyGames } from './dummyGames';

export interface GameNftData {
  address: PublicKey,
  title: string,
  description: string,
  cover: string,
  launchUrl: string,
  images: string[],
  tokenMint: PublicKey,
  itemsMint: PublicKey[],
}

export interface GamesNftStoreState {
  inProgress: PublicKey[],
  loaded: GameNftData[],
  failed: PublicKey[]
}

const initialState: GamesNftStoreState = {
  inProgress: [],
  loaded: [...dummyGames],
  failed: []
};

export const gamesNtfStoreSlice = createSlice({
  name: 'gamesNftStore',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {

  },
});

const selectState = (state: RootState) => state.gamesNftStore;

export const selectNftGames = (rootState: RootState, games: PublicKey[]) =>
{
  const state = selectState(rootState)

  const gamesInProgress = state.inProgress.filter(x => games.find(a => a === x));
  const gamesLoaded = state.loaded.filter(x => games.find(a => a === x.address));
  const gamesFailed = state.failed.filter(x => games.find(a => a === x));

  const result: Record<string, GameState> = {};

  gamesInProgress.forEach(x => result[x.toString()] = { status: 'inProgress' })
  gamesLoaded.forEach(x => result[x.address.toString()] = { status: 'loaded', game: x })
  gamesFailed.forEach(x => result[x.toString()] = { status: 'failed' })

  return result;
}

export interface GameState {
  status: GameLoadingStatus,
  game?: GameNftData
}

export type GameLoadingStatus = 'inProgress' | 'loaded' | 'failed'

export default gamesNtfStoreSlice.reducer;
