import { createSlice } from '@reduxjs/toolkit';

export interface GamesStorePageState {
}

const initialState: GamesStorePageState = {
};

export const gamesStorePageSlice = createSlice({
  name: 'gamesStorePage',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {

  },
});


export default gamesStorePageSlice.reducer;
